# PIPET Papers (2017-Present)
[1] S. H. Bae, D. Yim, H. Lee, et al. “Application of Pharmacometrics
in Pharmacotherapy: Open-Source Software for Vancomycin Therapeutic
Drug Management”. In: _Pharmaceutics_ 11.5 (May. 2019), p. 224. DOI:
10.3390/pharmaceutics11050224. <URL:
https://doi.org/10.3390/pharmaceutics11050224>.

[2] S. Cho, S. Han, J. Ghim, et al. “A Randomized, Double-Blind Trial
Comparing the Pharmacokinetics of CT-P16, a Candidate Bevacizumab
Biosimilar, with its Reference Product in Healthy Adult Males”. In:
_BioDrugs_ 33.2 (Mar. 2019), pp. 173-181. DOI:
10.1007/s40259-019-00340-x. <URL:
https://doi.org/10.1007/s40259-019-00340-x>.

[3] S. Choi, S. Han, S. Jeon, et al. “Quantitative Prediction of Human
Pharmacokinetics and Pharmacodynamics of CKD519, a Potent Inhibitor of
Cholesteryl Ester Transfer Protein (CETP)”. In: _Pharmaceutics_ 11.7
(Jul. 2019), p. 336. DOI: 10.3390/pharmaceutics11070336. <URL:
https://doi.org/10.3390/pharmaceutics11070336>.

[4] S. Han, S. Han, K. Kim, et al. “Usefulness of Bnet, a Simple Linear
Metric in Discerning Torsades De Pointes Risks in 28 CiPA Drugs”. In:
_Frontiers in Pharmacology_ 10 (Nov. 2019). DOI:
10.3389/fphar.2019.01419. <URL:
https://doi.org/10.3389/fphar.2019.01419>.

[5] T. M. Polasek, A. Rostami-Hodjegan, D. Yim, et al. “What Does it
Take to Make Model-Informed Precision Dosing Common Practice? Report
from the 1st Asian Symposium on Precision Dosing”. In: _The AAPS
Journal_ 21.2 (Jan. 2019). DOI: 10.1208/s12248-018-0286-6. <URL:
https://doi.org/10.1208/s12248-018-0286-6>.

[6] S. H. Bae, W. Park, S. Han, et al. “Physiologically-based
pharmacokinetic predictions of intestinal BCRP-mediated drug
interactions of rosuvastatin in Koreans”. In: _The Korean Journal of
Physiology & Pharmacology_ 22.3 (2018), p. 321. DOI:
10.4196/kjpp.2018.22.3.321. <URL:
https://doi.org/10.4196/kjpp.2018.22.3.321>.

[7] S. Choi, S. Jeon, and S. Han. “Population pharmacokinetic analysis
of metformin administered as fixed-dose combination in Korean healthy
adults”. In: _Translational and Clinical Pharmacology_ 26.1 (2018), p.
25. DOI: 10.12793/tcp.2018.26.1.25. <URL:
https://doi.org/10.12793/tcp.2018.26.1.25>.

[8] S. Han, B. Lim, H. Lee, et al. “Development of a user-friendly
training software for pharmacokinetic concepts and models”. In:
_Translational and Clinical Pharmacology_ 26.4 (2018), p. 166. DOI:
10.12793/tcp.2018.26.4.166. <URL:
https://doi.org/10.12793/tcp.2018.26.4.166>.

[9] D. Yim. “Five years of the CiPA project (2013\textendash2018): what
did we learn?” In: _Translational and Clinical Pharmacology_ 26.4
(2018), p. 145. DOI: 10.12793/tcp.2018.26.4.145. <URL:
https://doi.org/10.12793/tcp.2018.26.4.145>.

[10] S. Han, G. H. Na, and D. Kim. “A 6-month mixed-effect
pharmacokinetic model for post-transplant intravenous anti-hepatitis B
immunoglobulin prophylaxis”. In: _Drug Design, Development and Therapy_
Volume 11 (Jul. 2017), pp. 2099-2107. DOI: 10.2147/dddt.s134711. <URL:
https://doi.org/10.2147/dddt.s134711>.

[11] W. Huh, H. Oh, J. S. Han, et al. “Hydrochlorothiazide does not
increase furosemide's effects in end-stage renal disease”. In:
_Translational and Clinical Pharmacology_ 25.1 (2017), p. 28. DOI:
10.12793/tcp.2017.25.1.28. <URL:
https://doi.org/10.12793/tcp.2017.25.1.28>.

[12] D. Jang, S. Han, and D. Yim. “Development of an automated appendix
generation system (ARGUS) for clinical study reports”. In:
_Translational and Clinical Pharmacology_ 25.1 (2017), p. 34. DOI:
10.12793/tcp.2017.25.1.34. <URL:
https://doi.org/10.12793/tcp.2017.25.1.34>.

[13] G. Park, S. H. Bae, W. Park, et al.
“Drug&ndash$\mathsemicolon$drug interaction of microdose and
regular-dose omeprazole with a CYP2C19 inhibitor and inducer”. In:
_Drug Design, Development and Therapy_ Volume11 (Mar. 2017), pp.
1043-1053. DOI: 10.2147/dddt.s131797. <URL:
https://doi.org/10.2147/dddt.s131797>.

[14] W. Park, G. Park, S. Han, et al. “Human microdosing and mice
xenograft data of AGM-130 applied to estimate efficacious doses in
patients”. In: _Cancer Chemotherapy and Pharmacology_ 80.2 (Jun. 2017),
pp. 363-369. DOI: 10.1007/s00280-017-3373-y. <URL:
https://doi.org/10.1007/s00280-017-3373-y>.

[15] N. Rajasekaran, H. S. Jung, S. H. Bae, et al. “Effect of HPV E6/E7
siRNA with Chemotherapeutic Agents on the Regulation of TP53/E2F
Dynamic Behavior for Cell Fate Decisions”. In: _Neoplasia_ 19.10 (Oct.
2017), pp. 735-749. DOI: 10.1016/j.neo.2017.07.005. <URL:
https://doi.org/10.1016/j.neo.2017.07.005>.

[16] D. Yim. “Tutorial for beginners: the concept of clearance
explained using the example of a vacuum cleaner”. In: _Translational
and Clinical Pharmacology_ 25.1 (2017), p. 1. DOI:
10.12793/tcp.2017.25.1.1. <URL:
https://doi.org/10.12793/tcp.2017.25.1.1>.
